language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - pecl install riak
    - composer install --dev

script:
    - phpunit
    - vendor/bin/phpcs -np --extensions=php --ignore=vendor/*,Tests/* --standard=ruleset.xml .